import React, { useEffect, useMemo, useState } from 'react';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut, User } from 'firebase/auth';
import { addDoc, collection, deleteDoc, doc, onSnapshot, query, setDoc, where } from 'firebase/firestore';
import { Archive, Inbox, PenLine, Settings, Trash2 } from 'lucide-react';
import { auth, db, firebaseEnabled } from './services/firebase';
import { ensureUserProfile, removeDelivery, sendCard } from './services/delivery';
import { archiveDelivery, buildPrintableHtml, deleteArchiveCard, listArchive } from './services/archive';
import { parseRecipientNumber, validateDisplayName } from './services/validation';
import type { ArchiveCard, CardDraft, Contact, Delivery, UserProfile } from './types';
import './styles.css';

const blankDraft = (): CardDraft => ({ includeBack: true, front: { text: '' }, back: { text: '' } });

function AuthScreen() {
  const [mode, setMode] = useState<'signin'|'signup'>('signup'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [error,setError]=useState('');
  async function submit(e: React.FormEvent){ e.preventDefault(); setError(''); if(!auth) return setError('Add Firebase env vars to enable authentication.'); try { const cred = mode==='signup' ? await createUserWithEmailAndPassword(auth,email,password) : await signInWithEmailAndPassword(auth,email,password); if(mode==='signup') await ensureUserProfile(cred.user, name); } catch(err:any){ setError(err.message); } }
  return <main className="landing"><section className="hero"><p className="eyebrow">Carte / Pancarte</p><h1>A small card to one known person.</h1><p>No feeds, likes, comments, metrics, rankings, timelines, or followers. Just quiet postcards.</p></section><form className="panel auth" onSubmit={submit}><h2>{mode==='signup'?'Create your Carte':'Welcome back'}</h2>{mode==='signup'&&<input placeholder="Display name" value={name} onChange={e=>setName(e.target.value)} />}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} /><input type="password" minLength={6} placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} /><button className="primary">{mode==='signup'?'Sign up':'Sign in'}</button><button type="button" className="ghost" onClick={()=>setMode(mode==='signup'?'signin':'signup')}>{mode==='signup'?'I already have a Carte':'Create an account'}</button>{!firebaseEnabled&&<p className="error">Firebase is not configured yet; see README.</p>}{error&&<p className="error">{error}</p>}</form></main>
}

function CardPreview({draft, side, setSide}:{draft:CardDraft; side:'front'|'back'; setSide:(s:'front'|'back')=>void}){ const s=side==='front'?draft.front:draft.back; return <div className="postcard" onClick={()=>setSide(side==='front'?'back':'front')}><div className="stamp">{side}</div>{s?.imageUrl&&<img src={s.imageUrl} alt="card"/>}<p>{s?.text || 'Your quiet note will appear here.'}</p></div> }

function Compose({profile}:{profile:UserProfile}){ const [draft,setDraft]=useState(blankDraft); const [side,setSide]=useState<'front'|'back'>('front'); const [to,setTo]=useState(''); const [status,setStatus]=useState(''); const current=side==='front'?draft.front:(draft.back??{text:''}); function update(v:Partial<any>){ setDraft(d=>({...d,[side]:{...(side==='front'?d.front:d.back),...v}})); }
 async function send(){ setStatus(''); try{ await sendCard(profile,to,draft); setDraft(blankDraft()); setTo(''); setStatus('Sent.'); }catch(e:any){ setStatus(e.message || 'Send failed. Draft kept.'); } }
 return <section className="grid"><div className="panel"><h2>Write</h2><div className="tabs"><button className={side==='front'?'active':''} onClick={()=>setSide('front')}>Front</button><button className={side==='back'?'active':''} onClick={()=>setSide('back')}>Back</button></div><textarea value={current.text} onChange={e=>update({text:e.target.value})} placeholder="Write something small…"/><label className="file">Add photo<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0]; if(f) update({imageFile:f,imageUrl:URL.createObjectURL(f)});}}/></label><input inputMode="numeric" placeholder="Recipient Carte #" value={to} onChange={e=>setTo(e.target.value)} /><button className="primary" onClick={send}>Send carte</button>{status&&<p className="note">{status}</p>}<Contacts profile={profile} pick={n=>setTo(String(n))}/></div><CardPreview draft={draft} side={side} setSide={setSide}/></section> }

function Contacts({profile,pick}:{profile:UserProfile; pick:(n:number)=>void}){ const [items,setItems]=useState<Contact[]>([]); const [name,setName]=useState(''); const [num,setNum]=useState(''); useEffect(()=>{ if(!db) return; return onSnapshot(collection(db,'contacts',profile.uid,'items'), s=>setItems(s.docs.map(d=>({id:d.id,...d.data()} as Contact))));},[profile.uid]); async function add(){ if(!db) return; const err=validateDisplayName(name); if(err) return alert(err); await addDoc(collection(db,'contacts',profile.uid,'items'),{displayName:name.trim(),userNumber:parseRecipientNumber(num)}); setName(''); setNum(''); } return <div><h3>Contacts</h3><div className="row"><input placeholder="Name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="#" inputMode="numeric" value={num} onChange={e=>setNum(e.target.value)}/><button onClick={add}>Save</button></div><div className="chips">{items.map(c=><button key={c.id} onClick={()=>pick(c.userNumber)}>{c.displayName} #{c.userNumber}</button>)}</div></div> }

function Tray({profile,refreshArchive}:{profile:UserProfile; refreshArchive:()=>void}){ const [items,setItems]=useState<Delivery[]>([]); useEffect(()=>{ if(!db) return; return onSnapshot(query(collection(db,'deliveries'),where('recipientUid','==',profile.uid)), s=>setItems(s.docs.map(d=>({id:d.id,...d.data()} as Delivery))));},[profile.uid]); async function done(d:Delivery){ await archiveDelivery(profile.uid,d); await removeDelivery(d.id); refreshArchive(); } return <section><h2>In-tray</h2><div className="cards">{items.map(d=><Reader key={d.id} card={d} actions={<><button onClick={()=>done(d)}>Done</button><button className="danger" onClick={()=>removeDelivery(d.id)}>Erase</button></>}/>)}</div>{!items.length&&<p className="empty">Your tray is quiet.</p>}</section> }
function Reader({card,actions}:{card:Delivery|ArchiveCard; actions:React.ReactNode}){ const [back,setBack]=useState(false); const s=back?card.card.back:card.card.front; return <article className="reader"><p className="from">From {card.senderDisplayName} #{card.senderNumber}</p><div className="postcard small" onClick={()=>setBack(!back)}><div className="stamp">{back?'back':'front'}</div>{s?.imageUrl&&<img src={s.imageUrl}/>}<p>{s?.text}</p></div><div className="row">{card.card.back&&<button onClick={()=>setBack(!back)}>Flip</button>}{actions}</div></article> }
function ArchiveView({profile,items,reload}:{profile:UserProfile;items:ArchiveCard[];reload:()=>void}){ function print(c:ArchiveCard){ const w=open('','_blank'); if(w) w.document.write(buildPrintableHtml(c)); } return <section><h2>Archive</h2><p className="note">This archive is local IndexedDB: private and device-local, easy to export, but not synced across browsers.</p><div className="cards">{items.map(c=><Reader key={c.id} card={c} actions={<><button onClick={()=>print(c)}>Export PDF</button><button className="danger" onClick={async()=>{await deleteArchiveCard(profile.uid,c.id); reload();}}>Erase</button></>}/>)}</div></section> }
function App(){ const [user,setUser]=useState<User|null>(null); const [profile,setProfile]=useState<UserProfile|null>(null); const [tab,setTab]=useState('write'); const [archive,setArchive]=useState<ArchiveCard[]>([]); useEffect(()=>auth?onAuthStateChanged(auth,async u=>{setUser(u); if(u){ const p=await ensureUserProfile(u,u.email?.split('@')[0]??'Carte user'); setProfile(p); setArchive(await listArchive(u.uid));}}):undefined,[]); if(!user||!profile) return <AuthScreen/>; const reload=()=>listArchive(profile.uid).then(setArchive); return <><header><b>Carte</b><nav>{[['write',PenLine],['tray',Inbox],['archive',Archive],['me',Settings]].map(([t,I]:any)=><button className={tab===t?'active':''} onClick={()=>setTab(t)}><I size={16}/>{t}</button>)}</nav></header><main className="app">{tab==='write'&&<Compose profile={profile}/>} {tab==='tray'&&<Tray profile={profile} refreshArchive={reload}/>} {tab==='archive'&&<ArchiveView profile={profile} items={archive} reload={reload}/>} {tab==='me'&&<section className="panel"><h2>{profile.displayName}</h2><p className="number">#{profile.userNumber}</p><p>Share this Carte number with people you know.</p><button onClick={()=>auth&&signOut(auth)}>Sign out</button></section>}</main></> }
export default App;
